run:
  timeout: 5m
  tests: true
  go: "1.25"
  modules-download-mode: mod
  build-tags:
    - cgo
    # - server
    # - policy_wasm

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
