name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ai-governance-sidecar   # 👈 set working dir

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'

    - name: Verify go.mod
      run: |
        if [ ! -f go.mod ]; then
          echo "go.mod not found!"
          exit 1
        fi
        cat go.mod

    - name: Tidy dependencies
      run: go mod tidy

    - name: Run tests with coverage
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m
        working-directory: ./ai-governance-sidecar 

  build:
    name: Build Binary
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ai-governance-sidecar 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v -o governance-sidecar ./cmd/sidecar

    - name: Test binary
      run: |
        if [ -f governance-sidecar ]; then
          echo "Binary built successfully"
          ls -lh governance-sidecar
        else
          echo "Binary not found!"
          exit 1
        fi